spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://39.106.254.177:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

  resources:
    static-locations: classpath:static/,file:static/


comment.avatar: /images/avatar.png
